- name: Deploy via SSH (Docker)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/swiftypay-backend
            git pull origin main
            docker-compose down
            docker-compose up -d --build